# Generated by Django 3.2.1 on 2021-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
